@HostAddress = http://localhost:5225
@Version = v1


POST {{HostAddress}}/api/{{Version}}/createcategoryusingmediator
Content-Type: application/json
{
  "name": "Books_med_1",
  "image": "https://api.lorem.space/image/book?w=150&h=220"
}






###
