@HostAddress = http://localhost:5225
@Version = v1

GET {{HostAddress}}/api/{{Version}}/getproducts
Accept: application/json


GET {{HostAddress}}/api/{{Version}}/getproduct/{{id}}
Accept: application/json

POST {{HostAddress}}/api/{{Version}}/createproduct
Content-Type: application/json
{
    "title": "test-title-prod-1",
    "price": 10,
    "description": "test-descr-prod-1",
    "categoryId": 1,
    "images": [
        "https://placeimg.com/640/480/any"
    ]
}
###
