@HostAddress = http://localhost:5225
@Version = v1

# GET {{HostAddress}}/api/{{Version}}/getproduct
# Accept: application/json

# GET {{HostAddress}}/api/{{Version}}/getproduct/{{id}}
# Accept: application/json

# POST {{HostAddress}}/api/{{Version}}/createproduct
# Content-Type: application/json
# {
#     "title": "New Product_3",
#     "price": 10,
#     "description": "A description",
#     "categoryId": 1,
#     "images": [
#         "https://placeimg.com/640/480/any"
#     ]
# }




# GET {{HostAddress}}/api/{{Version}}/getcategories
# Accept: application/json

# GET {{HostAddress}}/api/{{Version}}/getcategory/1
# Accept: application/json

# POST {{HostAddress}}/api/{{Version}}/createcategory
# Content-Type: application/json
# {
#   "name": "Books1",
#   "image": "https://api.lorem.space/image/book?w=150&h=220"
# }


#GET {{HostAddress}}/api/{{Version}}/getproductsusingmediator
#Accept: application/json

# GET {{HostAddress}}/api/{{Version}}/getproductusingmediator/{{id}}
# Accept: application/json

# POST {{HostAddress}}/api/{{Version}}/createproductusingmediator
# Content-Type: application/json
# {
#     "title": "New Product_mid_1",
#     "price": 10,
#     "description": "A description",
#     "categoryId": 1,
#     "images": [
#         "https://placeimg.com/640/480/any"
#     ]
# }




#GET {{HostAddress}}/api/{{Version}}/getcategoriesusingmediator
#Accept: application/json

# GET {{HostAddress}}/api/{{Version}}/getcategoryusingmediator/{{id}}
# Accept: application/json

# POST {{HostAddress}}/api/{{Version}}/createcategoryusingmediator
# Content-Type: application/json
# {
#   "name": "Books_med-1",
#   "image": "https://api.lorem.space/image/book?w=150&h=220"
# }


###
